-- MySQL Script generated by MySQL Workbench
-- Thursday 26 October 2017 05:11:35 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `food_delivery` ;

-- -----------------------------------------------------
-- Schema food_delivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_delivery` DEFAULT CHARACTER SET utf8 ;
USE `food_delivery` ;

-- -----------------------------------------------------
-- Table `food_delivery`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `food_delivery`.`restaurant` (
  `id_restaurant` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `cuisine` VARCHAR(45) NULL,
  PRIMARY KEY (`id_restaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery`.`customer` ;

CREATE TABLE IF NOT EXISTS `food_delivery`.`customer` (
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NULL,
  `id_customer` INT NOT NULL,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`delivery_guy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery`.`delivery_guy` ;

CREATE TABLE IF NOT EXISTS `food_delivery`.`delivery_guy` (
  `id_delivery_guy` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_delivery_guy`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_delivery`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `food_delivery`.`order` ;

CREATE TABLE IF NOT EXISTS `food_delivery`.`order` (
  `food` VARCHAR(45) NULL,
  `total_cost` VARCHAR(45) NULL,
  `delivery_guy_id_delivery_guy` INT NOT NULL,
  `restaurant_id_restaurant` INT NOT NULL,
  `customer_id_customer` INT NOT NULL,
  INDEX `fk_order_delivery_guy_idx` (`delivery_guy_id_delivery_guy` ASC),
  INDEX `fk_order_restaurant1_idx` (`restaurant_id_restaurant` ASC),
  INDEX `fk_order_customer1_idx` (`customer_id_customer` ASC),
  CONSTRAINT `fk_order_delivery_guy`
    FOREIGN KEY (`delivery_guy_id_delivery_guy`)
    REFERENCES `food_delivery`.`delivery_guy` (`id_delivery_guy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_restaurant1`
    FOREIGN KEY (`restaurant_id_restaurant`)
    REFERENCES `food_delivery`.`restaurant` (`id_restaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `food_delivery`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
