-- MySQL Script generated by MySQL Workbench
-- Wednesday 01 November 2017 11:08:07 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema irctc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `irctc` ;

-- -----------------------------------------------------
-- Schema irctc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `irctc` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `irctc` ;

-- -----------------------------------------------------
-- Table `irctc`.`train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irctc`.`train` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `irctc`.`train` (
  `id_train` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `route` VARCHAR(45) NULL,
  `train_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id_train`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `irctc`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irctc`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `irctc`.`customer` (
  `id_customer` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `customercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `irctc`.`reserved_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irctc`.`reserved_ticket` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `irctc`.`reserved_ticket` (
  `id_reserved_ticket` INT NOT NULL,
  `start_time` DATE NOT NULL,
  `end_time` DATETIME NOT NULL,
  `price` VARCHAR(45) NULL,
  `train_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id_reserved_ticket`, `train_id`, `customer_id`),
  CONSTRAINT `fk_reserved_ticket_train`
    FOREIGN KEY (`train_id`)
    REFERENCES `irctc`.`train` (`id_train`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserved_ticket_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `irctc`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_reserved_ticket_train_idx` ON `irctc`.`reserved_ticket` (`train_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_reserved_ticket_customer1_idx` ON `irctc`.`reserved_ticket` (`customer_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `irctc`.`unreserved_ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `irctc`.`unreserved_ticket` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `irctc`.`unreserved_ticket` (
  `id_unreserved_ticket` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `price` VARCHAR(45) NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`id_unreserved_ticket`, `customer_id`),
  CONSTRAINT `fk_unreserved_ticket_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `irctc`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_unreserved_ticket_customer1_idx` ON `irctc`.`unreserved_ticket` (`customer_id` ASC);

SHOW WARNINGS;
USE `irctc`;

DELIMITER $$

USE `irctc`$$
DROP TRIGGER IF EXISTS `irctc`.`reserved_ticket_BEFORE_INSERT` $$
SHOW WARNINGS$$
USE `irctc`$$
CREATE DEFINER = CURRENT_USER TRIGGER `irctc`.`reserved_ticket_BEFORE_INSERT` BEFORE INSERT ON `reserved_ticket` FOR EACH ROW
BEGIN
IF(NEW.start_time < (SELECT reserved_ticket.end_time FROM reserved_ticket WHERE reserved_ticket.customer_id = NEW.customer_id))
		THEN SIGNAL SQLSTATE '45000';
		SET MESSAGE_TEXT = 'A customer cannot be in two trains at the same time.';
	END IF;
END;$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
