-- MySQL Script generated by MySQL Workbench
-- Wednesday 01 November 2017 11:31:32 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pe_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pe_project` ;

-- -----------------------------------------------------
-- Schema pe_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pe_project` ;
USE `pe_project` ;

-- -----------------------------------------------------
-- Table `pe_project`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pe_project`.`project` ;

CREATE TABLE IF NOT EXISTS `pe_project`.`project` (
  `id_project` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `domain` VARCHAR(45) NULL,
  `expected_duration` VARCHAR(45) NULL,
  `client_name` VARCHAR(45) NULL,
  `projectcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_project`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pe_project`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pe_project`.`employee` ;

CREATE TABLE IF NOT EXISTS `pe_project`.`employee` (
  `id_employees` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `joining_date` DATE NULL,
  `position` VARCHAR(45) NULL,
  `employeecol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_employees`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pe_project`.`project_employ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pe_project`.`project_employ` ;

CREATE TABLE IF NOT EXISTS `pe_project`.`project_employ` (
  `id_project` INT NOT NULL,
  `id_employees` INT NOT NULL,
  CONSTRAINT `employ_project`
    FOREIGN KEY (`id_project`)
    REFERENCES `pe_project`.`project` (`id_project`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `employ_manager`
    FOREIGN KEY (`id_employees`)
    REFERENCES `pe_project`.`employee` (`id_employees`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_project_UNIQUE` ON `pe_project`.`project_employ` (`id_project` ASC);

CREATE INDEX `employ_manager_idx` ON `pe_project`.`project_employ` (`id_employees` ASC);


-- -----------------------------------------------------
-- Table `pe_project`.`employ_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pe_project`.`employ_manager` ;

CREATE TABLE IF NOT EXISTS `pe_project`.`employ_manager` (
  `id_employees` INT NOT NULL,
  `id_manager` INT NOT NULL,
  CONSTRAINT `fk_employ_junior`
    FOREIGN KEY (`id_employees`)
    REFERENCES `pe_project`.`employee` (`id_employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employ_manager`
    FOREIGN KEY (`id_manager`)
    REFERENCES `pe_project`.`employee` (`id_employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_employees_UNIQUE` ON `pe_project`.`employ_manager` (`id_employees` ASC);

CREATE INDEX `fk_employ_manager_idx` ON `pe_project`.`employ_manager` (`id_manager` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
