-- MySQL Script generated by MySQL Workbench
-- Wednesday 01 November 2017 01:21:46 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`customer` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`customer` (
  `id_customer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`supplier` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`supplier` (
  `id_supplier` INT NOT NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `contact_info` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id_supplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`order` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`order` (
  `id_order` INT NOT NULL,
  `date` DATETIME NULL,
  `customer_id_customer` INT NOT NULL,
  PRIMARY KEY (`id_order`, `customer_id_customer`),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `ecommerce`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_customer1_idx` ON `ecommerce`.`order` (`customer_id_customer` ASC);


-- -----------------------------------------------------
-- Table `ecommerce`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`item` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`item` (
  `id_item` INT NOT NULL,
  `item_name` VARCHAR(45) NULL,
  `item_price` VARCHAR(45) NULL,
  `supplier_id_supplier` INT NOT NULL,
  `brand` VARCHAR(45) NULL,
  `order_id_order` INT NOT NULL,
  `order_customer_id_customer` INT NOT NULL,
  PRIMARY KEY (`id_item`, `supplier_id_supplier`),
  CONSTRAINT `fk_item_supplier`
    FOREIGN KEY (`supplier_id_supplier`)
    REFERENCES `ecommerce`.`supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_order1`
    FOREIGN KEY (`order_id_order` , `order_customer_id_customer`)
    REFERENCES `ecommerce`.`order` (`id_order` , `customer_id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_item_supplier_idx` ON `ecommerce`.`item` (`supplier_id_supplier` ASC);

CREATE INDEX `fk_item_order1_idx` ON `ecommerce`.`item` (`order_id_order` ASC, `order_customer_id_customer` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
