-- MySQL Script generated by MySQL Workbench
-- Wednesday 01 November 2017 11:23:11 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema car_rental
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `car_rental` ;

-- -----------------------------------------------------
-- Schema car_rental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_rental` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `car_rental` ;

-- -----------------------------------------------------
-- Table `car_rental`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rental`.`driver` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `car_rental`.`driver` (
  `id_driver` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `drivercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_driver`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_id_UNIQUE` ON `car_rental`.`driver` (`email_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `phone_number_UNIQUE` ON `car_rental`.`driver` (`phone_number` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `car_rental`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rental`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `car_rental`.`customer` (
  `id_customer` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `phone_number_UNIQUE` ON `car_rental`.`customer` (`phone_number` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_id_UNIQUE` ON `car_rental`.`customer` (`email_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `car_rental`.`cab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rental`.`cab` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `car_rental`.`cab` (
  `id_cab` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `model_name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `number_of_seats` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cab`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `car_rental`.`cab_and_driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rental`.`cab_and_driver` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `car_rental`.`cab_and_driver` (
  `id_cab_and_driver` INT NOT NULL,
  `driver_id_driver` INT NOT NULL,
  `cab_id_cab` INT NOT NULL,
  PRIMARY KEY (`id_cab_and_driver`),
  CONSTRAINT `fk_cab_and_driver_driver`
    FOREIGN KEY (`driver_id_driver`)
    REFERENCES `car_rental`.`driver` (`id_driver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cab_and_driver_cab1`
    FOREIGN KEY (`cab_id_cab`)
    REFERENCES `car_rental`.`cab` (`id_cab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_cab_and_driver_driver_idx` ON `car_rental`.`cab_and_driver` (`driver_id_driver` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_cab_and_driver_cab1_idx` ON `car_rental`.`cab_and_driver` (`cab_id_cab` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `car_rental`.`cab_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rental`.`cab_customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `car_rental`.`cab_customer` (
  `idcab_customer` INT NOT NULL,
  `cab_id_cab` INT NOT NULL,
  `customer_id_customer` INT NOT NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  PRIMARY KEY (`idcab_customer`),
  CONSTRAINT `fk_cab_customer_cab1`
    FOREIGN KEY (`cab_id_cab`)
    REFERENCES `car_rental`.`cab` (`id_cab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cab_customer_customer1`
    FOREIGN KEY (`customer_id_customer`)
    REFERENCES `car_rental`.`customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_cab_customer_cab1_idx` ON `car_rental`.`cab_customer` (`cab_id_cab` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_cab_customer_customer1_idx` ON `car_rental`.`cab_customer` (`customer_id_customer` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
